# Generated by Django 5.2.8 on 2026-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Workstation', max_length=100)),
                ('status', models.CharField(default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated_at',
        ),
    ]
