# Generated by Django 5.2.8 on 2026-04-20 07:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_candidate_options_remove_asset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='rating',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='final_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='improvement_areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='key_strengths',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('technical_skills', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('productivity', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.DecimalField(decimal_places=1, editable=False, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='PerformanceGoal',
        ),
    ]
